# Generated by Django 5.1.7 on 2025-08-17 14:59

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, help_text='Principal in UGX', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual simple interest rate, e.g. 30.00 for 30%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('maturity_months', models.PositiveIntegerField(default=8, help_text='Term length in months')),
                ('date_invested', models.DateField(default=datetime.date.today)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'date_invested'], name='savings_52__user_pr_d7b947_idx'), models.Index(fields=['date_invested'], name='savings_52__date_in_8ecd37_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Deposit amount in UGX', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt or reference number for this deposit', max_length=32, null=True)),
                ('date_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('cumulative_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fully_covered_weeks', models.JSONField(blank=True, default=list)),
                ('next_week', models.PositiveIntegerField(default=1)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_transactions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-date_saved'],
                'indexes': [models.Index(fields=['user_profile', 'date_saved'], name='savings_52__user_pr_157dc3_idx'), models.Index(fields=['date_saved'], name='savings_52__date_sa_78df18_idx')],
            },
        ),
    ]
