# Generated by Django 5.1.7 on 2025-08-17 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_project_options_alter_userprofile_options_and_more'),
        ('savings_52_weeks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='investment',
            name='savings_52__user_pr_d7b947_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='savings_52__date_in_8ecd37_idx',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='date_invested',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 15, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('fixed_deposit', 'Fixed Deposit'), ('savings_bond', 'Savings Bond'), ('mutual_fund', 'Mutual Fund'), ('real_estate', 'Real Estate'), ('other', 'Other')], default='fixed_deposit', help_text='Type of investment', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this investment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('matured', 'Matured'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the investment', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 15, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this transaction'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], default='deposit', help_text='Type of transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, help_text='Week number for 52-week challenge (1-52)', null=True),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user_profile', 'start_date'], name='savings_52__user_pr_08cb90_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['start_date'], name='savings_52__start_d_f128aa_idx'),
        ),
    ]
