# Generated by Django 5.1.7 on 2025-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_52_weeks', '0002_remove_investment_savings_52__user_pr_d7b947_idx_and_more'),
    ]

    operations = [
        # Remove obsolete fields that are no longer in the model
        migrations.RemoveField(
            model_name='savingstransaction',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='due_date',
        ),
        
        # Add new fields that are in our current model
        migrations.AddField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(
                choices=[
                    ('deposit', 'Deposit'),
                    ('withdrawal', 'Withdrawal'),
                    ('adjustment', 'Adjustment'),
                ],
                default='deposit',
                help_text='Type of transaction',
                max_length=20
            ),
        ),
        
        # Update existing fields to match current model
        migrations.AlterField(
            model_name='savingstransaction',
            name='receipt_number',
            field=models.CharField(
                blank=True,
                help_text='Receipt or reference number for this deposit',
                max_length=32,
                null=True
            ),
        ),
        
        # Ensure the fully_covered_weeks field is properly configured
        migrations.AlterField(
            model_name='savingstransaction',
            name='fully_covered_weeks',
            field=models.JSONField(blank=True, default=list),
        ),
        
        # Ensure the remaining_balance field is properly configured
        migrations.AlterField(
            model_name='savingstransaction',
            name='remaining_balance',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                max_digits=14
            ),
        ),
        
        # Ensure the cumulative_total field is properly configured
        migrations.AlterField(
            model_name='savingstransaction',
            name='cumulative_total',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                max_digits=14
            ),
        ),
        
        # Ensure the next_week field is properly configured
        migrations.AlterField(
            model_name='savingstransaction',
            name='next_week',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
