# Generated by Django 5.1.7 on 2025-08-17 18:30
from django.db import migrations, models


def add_transaction_type_column(apps, schema_editor):
    """
    Safely add transaction_type column on PostgreSQL only.
    SQLite does NOT support IF NOT EXISTS and fresh dev DBs
    already have the correct schema.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            ALTER TABLE savings_52_weeks_savingstransaction
            ADD COLUMN IF NOT EXISTS transaction_type varchar(20)
            NOT NULL DEFAULT 'deposit';
            """
        )


def remove_transaction_type_column(apps, schema_editor):
    """
    Reverse operation (PostgreSQL only).
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            ALTER TABLE savings_52_weeks_savingstransaction
            DROP COLUMN IF EXISTS transaction_type;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            'savings_52_weeks',
            '0002_remove_investment_savings_52__user_pr_d7b947_idx_and_more',
        ),
    ]

    operations = [
        # Remove obsolete fields that are no longer in the model
        migrations.RemoveField(
            model_name='savingstransaction',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='due_date',
        ),

        # --- SAFE add for transaction_type (Postgres only) ---
        migrations.RunPython(
            add_transaction_type_column,
            reverse_code=remove_transaction_type_column,
        ),

        # Keep Django's state in sync with the DB
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='savingstransaction',
                    name='transaction_type',
                    field=models.CharField(
                        max_length=20,
                        choices=[
                            ('deposit', 'Deposit'),
                            ('withdrawal', 'Withdrawal'),
                            ('adjustment', 'Adjustment'),
                        ],
                        default='deposit',
                        help_text='Type of transaction',
                    ),
                ),
            ],
        ),

        # Update existing fields to match current model
        migrations.AlterField(
            model_name='savingstransaction',
            name='receipt_number',
            field=models.CharField(
                blank=True,
                help_text='Receipt or reference number for this deposit',
                max_length=32,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name='savingstransaction',
            name='fully_covered_weeks',
            field=models.JSONField(blank=True, default=list),
        ),

        migrations.AlterField(
            model_name='savingstransaction',
            name='remaining_balance',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                max_digits=14,
            ),
        ),

        migrations.AlterField(
            model_name='savingstransaction',
            name='cumulative_total',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                max_digits=14,
            ),
        ),

        migrations.AlterField(
            model_name='savingstransaction',
            name='next_week',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
