# Generated by Django 5.1.7 on 2025-08-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_52_weeks', '0003_update_savingstransaction_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('matured', 'Matured')], default='fixed', help_text='Current status of the investment', max_length=20),
        ),
    ]
