# Generated by Django 5.1.7 on 2026-03-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_52_weeks', '0005_add_withdrawal_gwc_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment'), ('gwc_contribution', 'Transfer to GWC')], default='deposit', help_text='Type of transaction', max_length=20),
        ),
    ]
