# Generated by Django 5.2.14 on 2026-08-07 04:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_project_options_project_accepts_requests_and_more'),
        ('main_account', '0004_mainaccountwithdrawal_reversal_transaction_and_more'),
        ('savings_52_weeks', '0006_alter_savingstransaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(help_text='Date of first deposit in this cycle')),
                ('end_date', models.DateField(help_text='start_date + 52 weeks')),
                ('status', models.CharField(choices=[('active', 'Active'), ('awaiting_decision', 'Awaiting decision'), ('pot_available', 'Matured pot available'), ('settled', 'Settled')], db_index=True, default='active', max_length=32)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='BF carried in when starting a new cycle', max_digits=14)),
                ('amount_saved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot of cycle principal (excludes leftover BF)', max_digits=14)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='15% annualized interest accrued during the cycle (daily)', max_digits=14)),
                ('balance_brought_forward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Leftover after week 52 at maturity', max_digits=14)),
                ('matured_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_action', models.CharField(blank=True, help_text='transfer_all | start_new_cycle | transfer_pot', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_account_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_cycles', to='main_account.mainaccounttransaction')),
                ('seeded_next_cycle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_from_cycle', to='savings_52_weeks.savingscycle')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_cycles', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-start_date', '-cycle_number'],
            },
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='Personal 52-week cycle this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='savings_52_weeks.savingscycle'),
        ),
        migrations.AddIndex(
            model_name='savingscycle',
            index=models.Index(fields=['user_profile', 'status'], name='savings_52__user_pr_6f98e7_idx'),
        ),
        migrations.AddIndex(
            model_name='savingscycle',
            index=models.Index(fields=['user_profile', 'start_date'], name='savings_52__user_pr_f700ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savingscycle',
            unique_together={('user_profile', 'cycle_number')},
        ),
    ]
