# Generated by Django 5.1.7 on 2026-02-02 21:02

import django.db.models.deletion
import django.utils.timezone
import goat_farming.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_drop_extra_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_capacity', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagementFeeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_goats', models.PositiveIntegerField()),
                ('max_goats', models.PositiveIntegerField()),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['min_goats'],
                'unique_together': {('min_goats', 'max_goats')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goat_count', models.PositiveIntegerField()),
                ('goat_unit_price', models.DecimalField(decimal_places=2, default=Decimal('600000.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('management_fee_tier', models.ForeignKey(help_text='Management fee tier for this package', on_delete=django.db.models.deletion.PROTECT, to='goat_farming.managementfeetier')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('goats_allocated', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('allocated', 'Goats Allocated')], default='pending', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to='goat_farming.farm')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goat_farming.investmentpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_prefix', models.CharField(default=goat_farming.models.get_receipt_prefix, help_text='Auto-generated prefix (RCPT-YYYYMMDD)', max_length=20)),
                ('receipt_suffix', models.CharField(help_text='Enter the suffix from your receipt book (e.g., DCF001, DCF002)', max_length=20)),
                ('receipt_number', models.CharField(blank=True, help_text='Full receipt number (auto-generated from prefix + suffix)', max_length=50, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='goat_farming.packagepurchase')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='UserFarmAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_goats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='goat_farming.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_accounts', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['farm', 'user'],
                'unique_together': {('user', 'farm')},
            },
        ),
    ]
