# Generated by Django 5.1.7 on 2026-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentpackage',
            name='kids_per_goat',
            field=models.PositiveSmallIntegerField(default=2, help_text='Expected kids per goat at end of 14-month cycle'),
        ),
    ]
