# Generated by Django 5.1.7 on 2026-02-03 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_farming', '0002_add_kids_per_goat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagepurchase',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Purchase date (editable for backdating existing data)'),
        ),
        migrations.AlterField(
            model_name='userfarmaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Account creation date (editable for backdating existing data)'),
        ),
    ]
