# Generated by Django 5.1.7 on 2026-02-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_farming', '0003_make_created_purchase_dates_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfarmaccount',
            name='expected_kids',
            field=models.PositiveIntegerField(blank=True, help_text='Admin override for expected kids at end of cycle. Leave blank to use calculated value from package.', null=True),
        ),
    ]
