# Generated by Django 5.1.7 on 2026-02-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_drop_extra_columns'),
        ('goat_farming', '0004_add_expected_kids_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGFActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('sell_cash_out', 'Sell & Cash Out'), ('take_goats', 'Take Goats'), ('transfer', 'Transfer (Breeding → Commercial)')], help_text='Type of action requested', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='User notes or additional details', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgf_action_requests', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'CGF Action Request',
                'verbose_name_plural': 'CGF Action Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
