# Generated by Django 5.1.7 on 2026-02-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_farming', '0005_add_cgf_action_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgfactionrequest',
            name='goats_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of goats for this action (sell, take, or transfer)', null=True),
        ),
    ]
