# Generated by Django 5.2.14 on 2026-08-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_farming', '0007_add_farm_to_cgf_action_request'),
        ('main_account', '0004_mainaccountwithdrawal_reversal_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgfactionrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount credited to Main Account for transfer_to_main actions.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='cgfactionrequest',
            name='main_account_transaction',
            field=models.OneToOneField(blank=True, help_text='Main Account credit posted when matured CGF value is transferred.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cgf_action_request', to='main_account.mainaccounttransaction'),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='When this matured cycle was transferred/settled to Main Account (or otherwise closed).', null=True),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='settlement_action',
            field=models.ForeignKey(blank=True, help_text='CGF action that settled this purchase to Main Account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_purchases', to='goat_farming.cgfactionrequest'),
        ),
        migrations.AlterField(
            model_name='cgfactionrequest',
            name='request_type',
            field=models.CharField(choices=[('sell_cash_out', 'Sell & Cash Out'), ('take_goats', 'Take Goats'), ('transfer', 'Transfer (Breeding → Commercial)'), ('transfer_to_main', 'Transfer to Main Account')], help_text='Type of action requested', max_length=30),
        ),
    ]
