# Generated by Django 5.2.14 on 2026-09-07 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_farming', '0008_cgf_transfer_to_main_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentpackage',
            name='cycle_duration_months',
            field=models.PositiveSmallIntegerField(default=14, help_text='Production / goat maturity cycle duration in months for this package.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='investmentpackage',
            name='kids_per_goat',
            field=models.PositiveSmallIntegerField(default=2, help_text="Expected kids per goat at the end of this package's production cycle."),
        ),
    ]
