# Generated by Django 5.2.14 on 2026-09-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_farming', '0009_investmentpackage_cycle_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentpackage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When unchecked, members can no longer buy this package. Existing purchases keep their goats, cycle, and cash-out terms.'),
        ),
    ]
