# Generated by Django 5.1.7 on 2026-04-27 03:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwc', '0003_gwc_deposit_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwcdepositactivity',
            options={'ordering': ['-timestamp', '-pk'], 'verbose_name': 'GWC deposit activity', 'verbose_name_plural': 'GWC deposit activities'},
        ),
        migrations.AlterModelOptions(
            name='gwcfixeddeposit',
            options={'ordering': ['-start_date', '-pk'], 'verbose_name': 'GWC fixed deposit', 'verbose_name_plural': 'GWC fixed deposits'},
        ),
        migrations.RenameIndex(
            model_name='gwcfixeddeposit',
            new_name='gwc_gwcfixe_user_id_d39439_idx',
            old_name='gwc_fd_user_status_idx',
        ),
        migrations.AlterField(
            model_name='gwcfixeddeposit',
            name='early_withdrawal_penalty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Penalty as % (policy / internal).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='gwcfixeddeposit',
            name='minimum_lock_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Minimum days before early withdrawal (policy / internal).'),
        ),
        migrations.AlterField(
            model_name='gwcfixeddeposit',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount fixed (principal), UGX.', max_digits=16),
        ),
    ]
