# Generated by Django 5.1.7 on 2026-03-04 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproject',
            name='allowed_members',
            field=models.ManyToManyField(blank=True, help_text='Users who can view full details and participate in this project. Other users will only see a limited summary.', related_name='realestate_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
