# Generated by Django 5.1.7 on 2026-03-04 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_projects', '0002_alter_realestateproject_allowed_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproject',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of land being acquired (numeric value).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='realestateproject',
            name='land_size_unit',
            field=models.CharField(blank=True, help_text='Unit for land size, e.g. acres, hectares.', max_length=50),
        ),
        migrations.AddField(
            model_name='realestateproject',
            name='operational_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Operational/overhead costs for this project.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='realestateproject',
            name='vendor_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total money required by the vendor.', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='RealEstateProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_contribution', models.DecimalField(decimal_places=2, help_text='Agreed match contribution expected from this member.', max_digits=14)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this member has completed their required payments.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='realestate_projects.realestateproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'user'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RealEstateProjectTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='payment', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='realestate_projects.realestateprojectmembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='realestate_projects.realestateproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
