# Generated by Django 5.1.7 on 2026-03-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_projects', '0003_realestateproject_land_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateprojecttransaction',
            name='acquisition_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of plots/acres covered by this transaction.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='realestateprojecttransaction',
            name='acquisition_unit',
            field=models.CharField(blank=True, help_text='Unit for acquisition, e.g. plots, acres.', max_length=50),
        ),
        migrations.AddField(
            model_name='realestateprojecttransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Member's remaining balance after this transaction.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='realestateprojecttransaction',
            name='payment_status',
            field=models.CharField(choices=[('partial', 'Partially paid'), ('full', 'Fully paid')], default='partial', help_text='Whether this transaction leaves the member partially or fully paid.', max_length=20),
        ),
        migrations.AddField(
            model_name='realestateprojecttransaction',
            name='transaction_date',
            field=models.DateField(blank=True, help_text='Date when this transaction was made.', null=True),
        ),
    ]
