# Generated by Django 5.1.7 on 2026-03-12 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_projects', '0004_realestateprojecttransaction_acquisition_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateProjectActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('withdraw', 'Withdraw cash'), ('transfer_gwc', 'Transfer to GWC'), ('transfer_namayumba', 'Transfer to Namayumba estate')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount the user is requesting to withdraw or transfer.', max_digits=14)),
                ('available_at_request', models.DecimalField(decimal_places=2, help_text='Available amount at the time of request (for audit).', max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional note from the user describing this action.')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes about how the request was handled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='realestate_projects.realestateprojectmembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='realestate_projects.realestateproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_action_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
