# Generated by Django 5.1.7 on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate_projects", "0005_realestateprojectactionrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestateprojectactionrequest",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_requests",
                to="realestate_projects.realestateprojectmembership",
            ),
        ),
    ]
