# Generated by Django 5.1.7 on 2026-03-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_projects', '0006_alter_realestateprojectactionrequest_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateprojecttransaction',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='realestateprojectactionrequest',
            name='membership',
        ),
        migrations.DeleteModel(
            name='RealEstateProjectMembership',
        ),
    ]
