# Generated by Django 5.2.14 on 2026-08-01 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0004_mainaccountwithdrawal_reversal_transaction_and_more'),
        ('realestate_projects', '0007_remove_realestateprojecttransaction_membership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateprojectactionrequest',
            name='main_account_transaction',
            field=models.OneToOneField(blank=True, help_text='Main Account credit posted when a refund request is processed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realestate_refund_request', to='main_account.mainaccounttransaction'),
        ),
        migrations.AddField(
            model_name='realestateprojectactionrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_realestate_action_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestateprojectactionrequest',
            name='realestate_transaction',
            field=models.OneToOneField(blank=True, help_text='Project transaction posted when this request is processed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_request', to='realestate_projects.realestateprojecttransaction'),
        ),
        migrations.AlterField(
            model_name='realestateprojectactionrequest',
            name='action_type',
            field=models.CharField(choices=[('withdraw', 'Withdraw cash'), ('refund', 'Refund to Main Account'), ('transfer_gwc', 'Transfer to GWC'), ('transfer_namayumba', 'Transfer to Namayumba estate')], max_length=32),
        ),
    ]
