# Generated by Django 5.1.7 on 2025-08-14 08:39

import accounts.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_photo_upload_to)),
                ('account_number', models.CharField(blank=True, db_index=True, help_text='Format: MCSTGF-AB0001 (auto-generated).', max_length=32, null=True, unique=True)),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UG', unique=True)),
                ('national_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(blank=True, related_name='members', to='accounts.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('account_number__regex', '^MCSTGF-[A-Z]{2}\\d{4,}$'), ('account_number__isnull', True), _connector='OR'), name='account_number_format_ok')],
            },
        ),
    ]
