# Generated by Django 5.1.7 on 2025-08-17 14:58

import datetime
import django.core.validators
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 15, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be 5–32 characters (letters, numbers, or hyphen).', regex='^[A-Za-z0-9\\-]{5,32}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Include country code, e.g., +2567xxxxxxxx', max_length=128, null=True, region='UG', unique=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='idx_profile_user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['account_number'], name='idx_profile_acct'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['whatsapp_number'], name='idx_profile_whatsapp'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['national_id'], name='idx_profile_nin'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_number__isnull', False)), fields=('whatsapp_number',), name='uniq_whatsapp_when_set'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id__isnull', False)), fields=('national_id',), name='uniq_national_id_when_set'),
        ),
    ]
