# Generated by Django 5.2.14 on 2026-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_projectaccessrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='accepts_requests',
            field=models.BooleanField(default=True, help_text='Allow members to submit access requests for this project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='cycle_display',
            field=models.CharField(blank=True, help_text="e.g. '6 – 24 months' or 'First cycle Q1 2027'.", max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='dashboard_url_name',
            field=models.CharField(blank=True, help_text="Named URL for the project's dashboard, e.g. 'savings_52_weeks:member_dashboard'.", max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class, e.g. 'fa-piggy-bank'.", max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, help_text="Show in the Discover section to members who don't have access."),
        ),
        migrations.AddField(
            model_name='project',
            name='min_entry_display',
            field=models.CharField(blank=True, help_text="e.g. 'UGX 500,000' or 'UGX 50,000 / month'.", max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='rate_display',
            field=models.CharField(blank=True, help_text="e.g. '10% p.a.' or '18 – 25% per cycle'.", max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers appear first in Discover.'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('coming_soon', 'Coming soon'), ('closed', 'Closed')], default='open', help_text='Open = joinable; Coming soon = teaser only; Closed = no new members.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, help_text='Short marketing description shown on the Discover card.', max_length=255),
        ),
    ]
