# Generated by Django 5.2.14 on 2026-08-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_project_options_project_accepts_requests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy 52WSC withdrawal request', 'verbose_name_plural': 'Legacy 52WSC withdrawal requests'},
        ),
    ]
