# Generated by Django 5.2.14 on 2026-08-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_staff_announcement_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membernotification',
            new_name='accounts_me_user_id_26ff08_idx',
            old_name='accounts_me_user_id_7b0f0c_idx',
        ),
    ]
