# Generated by Django 5.2.14 on 2026-06-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(help_text='Explain what the member will learn from this video.')),
                ('youtube_url', models.URLField(help_text='Paste a full YouTube link (watch, youtu.be, or embed URL).', max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('category', models.CharField(choices=[('general', 'General & platform'), ('profile', 'Profile & account'), ('savings_52', '52 Weeks Saving Challenge'), ('fixed_savings', 'Fixed Savings'), ('gwc', 'Generational Wealth (GWC)'), ('cgf', 'Commercial Goat Farming'), ('cooperative', 'Cooperative Shareholding'), ('real_estate', 'Real Estate'), ('mesu', 'MESU Academy'), ('other', 'Other')], default='general', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within a category.')),
                ('is_published', models.BooleanField(default=True, help_text='Only published videos are visible to members.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help video',
                'verbose_name_plural': 'Help videos',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
