# Generated by Django 5.2.14 on 2026-06-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0002_remove_mesu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpvideo',
            name='category',
            field=models.CharField(choices=[('general', 'General & platform'), ('profile', 'Profile & account'), ('savings_52', '52 Weeks Saving Challenge'), ('fixed_savings', 'Fixed Savings'), ('gwc', 'Generational Wealth (GWC)'), ('cgf', 'Commercial Goat Farming'), ('cooperative', 'Cooperative Shareholding'), ('mesu', 'MESU Academy'), ('real_estate', 'Real Estate'), ('other', 'Other')], default='general', max_length=32),
        ),
    ]
