# Generated by Django 5.2.14 on 2026-08-30 03:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_rename_accounts_me_user_id_7b0f0c_idx_accounts_me_user_id_26ff08_idx'),
        ('main_account', '0007_alter_mainaccounttransaction_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('purpose', models.CharField(choices=[('business', 'Business expansion'), ('education', 'Education'), ('medical', 'Medical / emergency'), ('housing', 'Housing'), ('agriculture', 'Agriculture'), ('other', 'Other')], max_length=30)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('term_months', models.PositiveSmallIntegerField(default=12)),
                ('repayment_source', models.CharField(choices=[('main_account', 'Main Account'), ('main_account_and_salary', 'Main Account + salary'), ('business_income', 'Business income')], default='main_account', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], db_index=True, default='submitted', max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to disburse. Defaults to requested amount if left blank.', max_digits=14, null=True)),
                ('approved_term_months', models.PositiveSmallIntegerField(blank=True, help_text='Term to use at disbursement. Defaults to requested term.', null=True)),
                ('monthly_interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.015'), help_text='Monthly rate as a decimal. 0.015 means 1.5% per month.', max_digits=7)),
                ('committee_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_loan_applications', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Loan application',
                'verbose_name_plural': 'Loan applications',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('purpose', models.CharField(choices=[('business', 'Business expansion'), ('education', 'Education'), ('medical', 'Medical / emergency'), ('housing', 'Housing'), ('agriculture', 'Agriculture'), ('other', 'Other')], max_length=30)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_interest_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_installments', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('written_off', 'Written off')], db_index=True, default='active', max_length=20)),
                ('disbursed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('first_due_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan', to='loans.loanapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_loans', to=settings.AUTH_USER_MODEL)),
                ('disbursement_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loan', to='main_account.mainaccounttransaction')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_loans', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Member loan',
                'verbose_name_plural': 'Member loans',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('main_account', 'Main Account'), ('bank_transfer', 'Bank transfer')], max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('external_reference', models.CharField(blank=True, help_text='Bank receipt/reference provided by the member.', max_length=120)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='loan-receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('main_account_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayment', to='main_account.mainaccounttransaction')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_loan_repayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.memberloan')),
            ],
            options={
                'verbose_name': 'Loan repayment',
                'verbose_name_plural': 'Loan repayments',
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due now'), ('upcoming', 'Upcoming')], db_index=True, default='upcoming', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.memberloan')),
            ],
            options={
                'verbose_name': 'Loan installment',
                'verbose_name_plural': 'Loan installments',
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['user_profile', 'status', '-created_at'], name='loans_loana_user_pr_0372bb_idx'),
        ),
        migrations.AddIndex(
            model_name='memberloan',
            index=models.Index(fields=['user_profile', 'status', '-created_at'], name='loans_membe_user_pr_0d183f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan', '-posted_at'], name='loans_loanr_loan_id_a66ea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loaninstallment',
            unique_together={('loan', 'installment_number')},
        ),
    ]
