# Generated by Cursor on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberloan",
            name="receipt_number",
            field=models.CharField(
                blank=True,
                help_text="Receipt/reference number for existing loans entered manually.",
                max_length=120,
            ),
        ),
    ]
