# Generated by Django 5.2.14 on 2026-09-05 03:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanrepayment_outstanding_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.015'), help_text='Monthly rate as a decimal. 0.015 = 1.5% (members), 0.01 = 1% (MCS staff).', max_digits=7),
        ),
    ]
