# Generated by Django 5.2.14 on 2026-07-12 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_alter_project_options_project_accepts_requests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('credit', 'Credit (money in)'), ('debit', 'Debit (money out)')], max_length=10)),
                ('category', models.CharField(choices=[('opening_balance', 'Opening balance'), ('admin_credit', 'Admin credit'), ('project_transfer_in', 'Transfer from project'), ('dividend', 'Dividend payout'), ('project_investment', 'Investment into project'), ('withdrawal', 'Withdrawal to bank'), ('adjustment', 'Adjustment / correction')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_label', models.CharField(blank=True, max_length=160)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/user who posted this entry (blank for system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_main_account_transactions', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_account_transactions', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Main account transaction',
                'verbose_name_plural': 'Main account transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MainAccountWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_main_account_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='main_account.mainaccounttransaction')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_account_withdrawals', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Main account withdrawal',
                'verbose_name_plural': 'Main account withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_label', models.CharField(help_text="Source project, e.g. 'Commercial Goat Farming'.", max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('member_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_project_transfers', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_transfer', to='main_account.mainaccounttransaction')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transfer_requests', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Project transfer request',
                'verbose_name_plural': 'Project transfer requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mainaccounttransaction',
            index=models.Index(fields=['user_profile', '-created_at'], name='idx_matx_profile_time'),
        ),
    ]
