# Generated by Django 5.2.14 on 2026-07-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMainAccountCredit',
            fields=[
            ],
            options={
                'verbose_name': 'Credit member main account',
                'verbose_name_plural': 'Credit member main account',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_account.mainaccounttransaction',),
        ),
    ]
