# Generated by Django 5.2.14 on 2026-08-01 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0003_mainaccountwithdrawal_payout_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mainaccountwithdrawal',
            name='reversal_transaction',
            field=models.OneToOneField(blank=True, help_text='Credit transaction posted when an approved withdrawal is reversed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_withdrawal', to='main_account.mainaccounttransaction'),
        ),
        migrations.AddField(
            model_name='mainaccountwithdrawal',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainaccountwithdrawal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_main_account_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainaccountwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
    ]
