# Generated by Django 5.2.14 on 2026-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0005_project_transfer_to_main_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainaccountwithdrawal',
            name='funding_note',
            field=models.TextField(blank=True, help_text="Snapshot of Main Account credits from projects/dividends at request time, so approvers can see where the member's funds came from."),
        ),
    ]
