# Generated by Django 5.2.14 on 2026-08-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0006_withdrawal_funding_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainaccounttransaction',
            name='category',
            field=models.CharField(choices=[('opening_balance', 'Opening balance'), ('admin_credit', 'Admin credit'), ('project_transfer_in', 'Transfer from project'), ('dividend', 'Dividend payout'), ('loan_disbursement', 'Loan disbursement'), ('project_investment', 'Investment into project'), ('loan_repayment', 'Loan repayment'), ('withdrawal', 'Withdrawal to bank'), ('adjustment', 'Adjustment / correction')], max_length=30),
        ),
    ]
