# Generated by Django 5.2.14 on 2026-06-04 02:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_share_price', models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Current cooperative share price in UGX.', max_digits=14)),
                ('dividend_rate', models.DecimalField(decimal_places=4, default=Decimal('0.26'), help_text='Dividend rate as decimal (0.26 = 26%).', max_digits=7)),
                ('reinvest_share_price', models.DecimalField(decimal_places=2, default=Decimal('1000000'), help_text='Price per share when reinvesting dividends (MCS premium class).', max_digits=14)),
                ('usd_to_ugx_rate', models.DecimalField(decimal_places=2, default=Decimal('3800'), max_digits=14)),
                ('blue_diamond_usd_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000000'), max_digits=14)),
                ('dividend_election_open', models.BooleanField(default=False, help_text='When enabled, members with holdings can submit dividend choices.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cooperative settings',
                'verbose_name_plural': 'Cooperative settings',
            },
        ),
        migrations.CreateModel(
            name='CooperativeShareholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_joined', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certificate_status', models.CharField(blank=True, choices=[('issued', 'Issued'), ('pending', 'Pending'), ('not_issued', 'Not issued')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_shareholding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cooperative shareholding',
                'verbose_name_plural': 'Cooperative shareholdings',
            },
        ),
        migrations.CreateModel(
            name='DividendChoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('cash', 'Cash (MoMo / bank)'), ('more_shares', 'Purchase more shares'), ('savings', 'MCS Fixed Savings (7.5% p.a.)')], max_length=20)),
                ('dividend_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('shares_to_reinvest', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('member_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('shareholding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_choices', to='cooperative_shareholding.cooperativeshareholding')),
            ],
            options={
                'verbose_name': 'Dividend choice request',
                'verbose_name_plural': 'Dividend choice requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareAcquisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=64)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('shares_held', models.PositiveIntegerField(default=0)),
                ('share_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('shareholding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_lines', to='cooperative_shareholding.cooperativeshareholding')),
            ],
            options={
                'verbose_name': 'Share acquisition line',
                'verbose_name_plural': 'Share acquisition lines',
                'ordering': ['-acquisition_date', '-pk'],
            },
        ),
    ]
