# Generated by Django 5.1.7 on 2026-06-04 04:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative_shareholding', '0005_acquisition_source_and_ledger_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativeglobaldefaults',
            name='blue_diamond_usd_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000'), help_text='USD equivalent for Blue Diamond tier.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='cooperativeglobaldefaults',
            name='reinvest_share_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000'), help_text='Price per share when reinvesting dividends (separate from cooperative book).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='cooperativeissuanceperiod',
            name='name',
            field=models.CharField(help_text="Label, e.g. 'December 2025 dividend issuance'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='cooperativeissuanceperiod',
            name='usd_to_ugx_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3800'), help_text='USD to UGX rate for this issuance period.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='cooperativeshareholding',
            name='current_share_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Current cooperative share price in UGX for this member.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='cooperativeshareholding',
            name='dividend_election_open',
            field=models.BooleanField(default=False, help_text='When enabled, this member can submit a dividend payout choice.'),
        ),
        migrations.AlterField(
            model_name='cooperativeshareholding',
            name='dividend_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.26'), help_text='Dividend rate as decimal (0.26 = 26%).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='cooperativeshareholding',
            name='issuance_period',
            field=models.ForeignKey(blank=True, help_text='USD rate period for Blue Diamond tier (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shareholdings', to='cooperative_shareholding.cooperativeissuanceperiod'),
        ),
    ]
