# Generated by Django 5.2.14 on 2026-06-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative_shareholding', '0007_dividend_disbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendallocationline',
            name='action_type',
            field=models.CharField(choices=[('cash', 'Cash (MoMo / bank)'), ('mcs_shares', 'MCS cooperative shares (UGX 1M/share)'), ('savings', 'MCS Fixed Savings (7.5% p.a.)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dividendallocationline',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, help_text='Whole shares for MCS cooperative reinvestment lines.'),
        ),
        migrations.AlterField(
            model_name='dividenddisbursement',
            name='fulfillment_type',
            field=models.CharField(choices=[('cash_paid', 'Cash paid (MoMo / bank)'), ('mcs_reinvest', 'Reinvested in MCS shares'), ('savings_deposit', 'Fixed / compulsory deposit')], max_length=20),
        ),
    ]
