# Generated by Django 5.2.14 on 2026-06-16 02:18

from decimal import Decimal
from django.db import migrations, models


def _effective_purchase_price(line) -> Decimal:
    if line.price_per_share and line.price_per_share > 0:
        return line.price_per_share
    if line.shares_held and line.share_amount:
        return (line.share_amount / Decimal(line.shares_held)).quantize(Decimal("1"))
    return Decimal("0")


def backfill_acquisition_valuations(apps, schema_editor):
    ShareAcquisitionLine = apps.get_model("cooperative_shareholding", "ShareAcquisitionLine")
    CooperativeGlobalDefaults = apps.get_model(
        "cooperative_shareholding", "CooperativeGlobalDefaults"
    )
    defaults, _ = CooperativeGlobalDefaults.objects.get_or_create(pk=1)
    new_price = defaults.new_share_purchase_price
    legacy_value = defaults.legacy_dividend_value_per_share

    for line in ShareAcquisitionLine.objects.all():
        purchase_price = _effective_purchase_price(line)
        if purchase_price >= new_price:
            line.current_value_per_share = purchase_price
            line.dividend_eligible = False
        elif purchase_price > 0:
            line.current_value_per_share = legacy_value
            line.dividend_eligible = True
        else:
            line.current_value_per_share = legacy_value
            line.dividend_eligible = True
        line.save(update_fields=["current_value_per_share", "dividend_eligible"])


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative_shareholding', '0008_remove_mesu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativeglobaldefaults',
            name='legacy_dividend_value_per_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Current value per share for lots purchased below the new-share price (e.g. UGX 100,000 as at 31 Dec 2025). Used for dividend calculation.', max_digits=14),
        ),
        migrations.AddField(
            model_name='cooperativeglobaldefaults',
            name='new_share_purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000'), help_text='Purchase price per share at or above this amount marks a new-era lot: valued at purchase price and not eligible for the legacy dividend cycle.', max_digits=14),
        ),
        migrations.AddField(
            model_name='shareacquisitionline',
            name='current_value_per_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Current value of one share in this lot (auto-calculated from purchase price).', max_digits=14),
        ),
        migrations.AddField(
            model_name='shareacquisitionline',
            name='dividend_eligible',
            field=models.BooleanField(default=True, help_text='Whether this lot is included in the current legacy dividend cycle. Lots purchased at the new-share price are excluded until a future cycle.'),
        ),
        migrations.AlterField(
            model_name='cooperativeshareholding',
            name='current_share_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Legacy field — per-lot values on acquisition lines drive portfolio and dividend totals. Kept for admin reference only.', max_digits=14),
        ),
        migrations.RunPython(backfill_acquisition_valuations, migrations.RunPython.noop),
    ]
