# Generated by Django 5.2.14 on 2026-06-16 03:11

import cooperative_shareholding.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative_shareholding', '0009_per_lot_share_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareacquisitionline',
            name='shares_held',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Number of shares in this lot (steps of 0.5 only, e.g. 1, 1.5, 2).', max_digits=12, validators=[cooperative_shareholding.models.validate_share_quantity_step]),
        ),
    ]
