# Generated by Django 5.2.14 on 2026-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative_shareholding', '0010_fractional_shares_half_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendallocationline',
            name='action_type',
            field=models.CharField(choices=[('cash', 'Cash (MoMo / bank)'), ('main_account', 'Main Account (for withdrawal)'), ('mcs_shares', 'MCS cooperative shares (UGX 1M/share)'), ('savings', 'MCS Fixed Savings (7.5% p.a.)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dividenddisbursement',
            name='fulfillment_type',
            field=models.CharField(choices=[('cash_paid', 'Cash paid (MoMo / bank)'), ('main_account_credit', 'Credited to Main Account'), ('mcs_reinvest', 'Reinvested in MCS shares'), ('savings_deposit', 'Fixed / compulsory deposit')], max_length=20),
        ),
    ]
